const tiles = [
    'Dragon Med Helm',
    'Ruby Amulet',
    'Obsidian Cape',
    'Abyssal Whip',
    'Dragon Square Shield',
    'Dragon Chainmail',
    'Obsidian Platelegs',
    'Climbing Boots (g)',
    'Beserker Ring',
    'Serpentine Visage',
    'Occult Necklace',
    "The Demon's Heart",
    'Staff of the Dead',
    'Magic Fang',
    'Ahrims Top',
    'Ahrims Bottom',
    'Aranea Boots',
    'Seers Ring',
    'Torva/Inquis Helmet',
    'Araxyte Fang',
    'Infernal Cape',
    'Scythe of Vitur',
    'Any Sigil (Corp)',
    'Torva/Inquis Top',
    'Torva/Inquis Bottom',
    'Primordial Crystal',
    'Ultor Vestige',
    'Sanguine/Holy Orn Kit',
    'Black Mask',
    'Onyx',
    'Fire Cape',
    'Zombie Axe (Broken)',
    "Mage's Book",
    'Fighters Torso',
    'Mystic Robe Bottom (dark)',
    'Dragon Boots',
    'Granite Gloves',
    'Guild Hunter Headwear',
    'Petal Garland',
    'Log Basket',
    'Dragon Pickaxe',
    'Abyssal Lantern',
    'Smiths Tunic',
    'Smiths Trousers',
    "Carpenter's Boots",
    'Superior Mining Gloves',
    '1 Crystal Armour Seed',
    'Enhanced Weapon Seed',
    'Crystal Tool Seed',
    '3 Crystal Armour Seed',
    '2 Crystal Armour Seed',
    'Elven signet',
    'Dagon Hai Hat',
    'Voidwaker Gem',
    'Voidwaker Blade',
    'Voidwaker Hilt',
    'Malediction Shard 1',
    'Malediction Shard 2',
    'Malediction Shard 3',
    'Dagon Hai Top',
    'Dagon Hai Bottom',
    'Treasonous Ring',
    'Granite Helm',
    'Amulet of Eternal Glory',
    '500 Ape Atoll Laps',
    "Bryophyta's Essence",
    'Dragon Metal Slice',
    'Ancient Ceremonial Top',
    "Monk's Robe (g)",
    'Holy Sandals',
    "Drake's Tooth",
    'Armadyl Helmet',
    'Any God Blessing',
    'Godsword Hilt (Any)',
    'Godsword Shard 1',
    'Godsword Shard 2',
    'Godsword Shard 3',
    'Armadyl Chestplate',
    'Bandos Tassets',
    'Bandos Boots',
    'Raids Hat',
    'Zenyte Shard',
    'Nihil Horn',
    'Armadyl Crossbow',
    'Elidinis Ward',
    'Raids Top',
    'Raids Bottom',
    'Pegasian Crystal',
    'Magus Icon',
    'Twisted Orn Kit',
    'Mutagen',
    'Dragonbone Necklace',
    "Vorkath's Head",
    'Zamorakian Hasta',
    "Hydra's Claw",
    'Any Visage Shield',
    'Void Knight Top',
    'Void Knight Robe',
    'Hydra Leather',
    'Farmers Strawhat',
    "Alchemist's Amulet",
    'Lost Bag',
    'Dragon Harpoon',
    'Smouldering Stone',
    'Tome Of Water',
    'Angler Top',
    'Angler Waders',
    'Farmers Boots',
    'Ring of Endurance',
    'Twitchers Gloves',
    'Blood Moon Helm',
    'Pendant of Ates',
    "Dizana's Quiver",
    'Dragonhunter Wand',
    'Tome of Earth',
    'Sunfire Fanatic Cuirass',
    'Eclipse Moon Tasset',
    'Echo Crystal',
    'Dragon Full Helm',
    'Gnome Scarf',
    'Raids Weapon',
    'Wyvern Visage',
    'Dragon Metal Lump',
    'Elder Chaos Robe',
    "Zealot's Boots",
];
export default tiles;
