const tiles = [
    'Mudskipper hat',
    'Big Harpoonfish',
    'KQ Head',
    'Warped Sceptre',
    'Demon Dung',
    'Curved Bone',
    'Chompy pet',
    'Grubs à la mode',
    'Raticide',
    'Orange (hat)',
    'Damp Tinderbox',
    'Cat Training Medal',
    'Burnt Oomlie Wrap',
    'Rod Dust',
    'Ferret',
    'Bravery Potion',
    'Servery Meat Pie',
    'Trollweiss',
    "Zamorak's Unfermented Wine",
    '2 Million Runecraft XP',
    '2 Million Woodcutting XP',
    '2 Million Fishing XP',
    '2 Million Agility XP',
    '2 Million Thieving XP',
    '2 Million Crafting XP',
    '2 Million Mining XP',
    '2 Million Smithing XP',
    'Voidwaker Blade',
    'Voidwaker Hilt',
    'Voidwaker Gem',
    'Any Elder Chaos Druid Robes Piece',
    'Fedora',
    'Malediction Shard 1',
    'Malediction Shard 2',
    'Malediction Shard 3',
    'Goblinicide',
    'Vorkath Speed-Chaser',
    'Zulrah Speed-Chaser',
    'Perfect Zulrah',
    'Two-Down',
    'Immortal Raid Team',
    "You Didn't Say Anything About a Bat",
    'Chompington',
    'Hespori Speed Chaser',
    'Fire Fighter',
    'Borisicide',
    'Fight Caves Speed-Runner',
    'Hueycoatl Speed-Runner',
    'Nex Duo',
    'No Toppings, No Drinks, Thanks',
    'But... Damage',
    'Theatre of Blood: SM Speed-Chaser',
    'One-Off',
    'Back in My Day...',
    "Pirate's Hook",
    'Onyx',
    'Zenyte Shard',
    "Ghrazi Rapier or Osmumten's Fang",
    'Shoulder Parrot',
    'Booty',
    'Teleport Anchoring Scroll',
    'Pop the Bloat',
    'Jakeicide',
    'Eye of Ayak',
    'Mokhaiotl Cloth',
    'Avernic Treads',
    'Zombie Axe',
    'Nightmare Pancake',
    'Any Shield Visage',
    'Granite Hammer',
    'Dragon Warhammer',
    'Tortoisicide',
    'Any Snake or Spider Pet',
    "Scorpia's Offspring",
    'Serpentine Visage',
    'Treasonous Ring',
    'Aranea Boots',
    'Araxyte Fang',
    'Tanzanite Fang',
    'Snakeicide',
    'Mask of Ranul',
    'Full Ancient Ceremonial Robes Set',
    'Any Nex Drop',
    'Dragon Boots',
    'Zamorakian Spear',
    'Staff of the Dead or Zamorak hilt',
    'Fragment of Seren Speed-Trialist',
    "Saradomin's Light",
    'Armadyl Crossbow or Saradomin Hilt',
    'Bandos Chestplate or Bandos Tassets',
    'Nexicide',
    '2 Crystal Armour Seed (1)',
    '2 Crystal Armour Seed (2)',
    'Enhanced Weapon Seed',
    'Crystal Tool Seed',
    'Enhanced Crystal Teleport Seed',
    'Elven Signet',
    'Rabbicide',
    'Greenman Mask',
    'All 3 nagua weapons',
    "Dizana's Quiver",
    'Dragonhunter Wand',
    'Tome of Earth',
    '3x Any Sunfire Fanatic Piece or Tonalztics of Ralos',
    'Complete a Set of Moons Gear',
    'Echo Crystal',
    'Dexterous or Arcane Prayer Scroll',
    'Ancestral Robes Piece',
    "D Claws/Dinh's Bulwark/DHCB/Twisted Buckler",
    'Elder Maul/Kodai/Twisted Bow',
    "Elidinis' Ward/Lightbearer",
    'Masori Armour Piece',
    "Tumeken's Shadow",
    'Avernic Defender Hilt or Sanguinesti Staff',
    'Justiciar Armour Piece',
    'Scythe of Vitur',
    'Ranger or Wizard Boots',
    'Spiked Manacles or Holy Sandles',
    'Cabbage Round Shield or Either Leprechaun Hat',
    'Power Ranger',
    'Any Mega-Rare Clue Table Drop',
    'Vestment Robe Set',
    'Master Scroll Book (empty)',
];
export default tiles;
