const tiles = [
    'Venator Blood Shard',
    'Elder Venator Fang/Kisten',
    'Gold Ring or Ultor Vestige from Vardorvis',
    'Hydra Leather',
    'Avernic Defender Hilt',
    'Varlamore Only',
    'Any BIG Fish from Trawling',
    'Abyssal Dagger',
    'Dragon Cannon Barrel',
    '2M Slayer XP',
    'Jar of Light',
    'Varlamore Achievement Diary',
    'Raids Hat',
    'Raids Top',
    'Raids Legs',
    'Any Transmog from CoX, ToB or Fang kit from ToA (Fang Kit must be a clog)',
    'Soon... (Tormented Synapse)',
    'Bronzeman Mode',
    'Uncut Onyx',
    'Kalphite Queen Head',
    'Venator Shard',
    'Sunfire Piece',
    'Any Revenant Weapon Upgrade',
    'Doom Unique',
    '50 Oathplate Shards or Oathplate Piece',
    'Bandos Boots',
    'Full Barrows Set (Any Combination of Helm, Body, Legs, and Weapon)',
    'Superior Table Drop',
    '2M Hunter XP',
    'Blessed Spirit Shield',
];

export default tiles;
